//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.MutualFunds
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_FundOptions
    {
        public MF_FundOptions()
        {
            this.MF_Funds = new HashSet<MF_Funds>();
        }
    
        public int OptionId { get; set; }
        public string FundOption { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<MF_Funds> MF_Funds { get; set; }
    }
}
