//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.MutualFunds
{
    using System;
    using System.Collections.Generic;
    
    public partial class MF_Transactions
    {
        public int TransactionId { get; set; }
        public int PortfolioId { get; set; }
        public int FolioId { get; set; }
        public int FundId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Amount { get; set; }
        public decimal PurchaseNAV { get; set; }
        public decimal Units { get; set; }
        public decimal Dividend { get; set; }
        public Nullable<decimal> ActualNAV { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
        public Nullable<decimal> SellNAV { get; set; }
        public Nullable<decimal> SellSTT { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual MF_Folios MF_Folios { get; set; }
        public virtual MF_Funds MF_Funds { get; set; }
        public virtual MF_Portfolios MF_Portfolios { get; set; }
    }
}
