//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.MutualFunds
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalFinanceEntities : DbContext
    {
        public PersonalFinanceEntities()
            : base("name=PersonalFinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MF_Folios> MF_Folios { get; set; }
        public DbSet<MF_FundCategory> MF_FundCategory { get; set; }
        public DbSet<MF_FundHouses> MF_FundHouses { get; set; }
        public DbSet<MF_FundOptions> MF_FundOptions { get; set; }
        public DbSet<MF_Funds> MF_Funds { get; set; }
        public DbSet<MF_FundTypes> MF_FundTypes { get; set; }
        public DbSet<MF_Portfolios> MF_Portfolios { get; set; }
        public DbSet<MF_Transactions> MF_Transactions { get; set; }
    }
}
