CREATE TABLE [dbo].[MF_SIPS](
	[SIPId] [bigint] IDENTITY(1,1) NOT NULL,
	[SchemaCode] [int] NOT NULL,
	[PortfolioId] [int] NOT NULL,
	[FromDate] [date] NOT NULL,
	[ToDate] [date] NOT NULL,
	[Amount] [int] NULL,
	[IsActive] [nvarchar](1) NOT NULL CONSTRAINT [DF_MF_SIPS_IsActive]  DEFAULT (N'N'),
	[SIPDate] [int] NOT NULL,
	[Frequency] [nvarchar](50) NULL,
	[CreateDate] [datetime] NOT NULL CONSTRAINT [DF_MF_SIPS_CreatedDate] DEFAULT (getdate()),
	[LastModifiedDate] DATETIME CONSTRAINT [DF_MF_SIPS_LastModifiedDate] DEFAULT (getdate()) NOT NULL,
 CONSTRAINT [PK_MF_SIPS] PRIMARY KEY CLUSTERED 
(
	[SIPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MF_SIPS]  WITH CHECK ADD  CONSTRAINT [FK_MF_SIPS_MF_SIPS] FOREIGN KEY([PortfolioId])
REFERENCES [dbo].[MF_Portfolios] ([PortfolioId])
GO

ALTER TABLE [dbo].[MF_SIPS] CHECK CONSTRAINT [FK_MF_SIPS_MF_SIPS]
GO

ALTER TABLE [dbo].[MF_SIPS]  WITH CHECK ADD  CONSTRAINT [FK_MF_SIPS_MF_SIPS1] FOREIGN KEY([SIPId])
REFERENCES [dbo].[MF_SIPS] ([SIPId])
GO

ALTER TABLE [dbo].[MF_SIPS] CHECK CONSTRAINT [FK_MF_SIPS_MF_SIPS1]
GO

