CREATE TABLE [dbo].[Budget] (
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FromDate] [date] NOT NULL CONSTRAINT DF_Budget_FromDate DEFAULT(GETDATE()),
	[ToDate] [date] NOT NULL CONSTRAINT DF_Budget_ToDate DEFAULT(GETDATE()),
	[Group] [nvarchar](100) NOT NULL CONSTRAINT DF_Budget_Group DEFAULT(' '),
	[Amount] [decimal](18, 4) NOT NULL CONSTRAINT DF_Budget_Amount DEFAULT(0),
	[CreatedDate] [datetime] NOT NULL CONSTRAINT DF_Budget_CreatedDate DEFAULT(GETDATE())
 CONSTRAINT [PK_Budget] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO